### ISSUE TITLE
Checkpoint 1 is ready

### ISSUE THREAD

**Issue by jbjohnson2** [jbjohnson2/indieProject#1]
@pawaitemadison college
Indie project checkpoint 1 ready for review

**Comment by pawaitemadisoncollege** [comment]
Hi @jbjohnson2 

Thanks for sharing your indie project checkpoint 1! You are off to a very solid start (I see some code already!) and have such a fun and useful project to work on. 

Following are my observations and suggestions:

**Problem statement**

Does a good job laying out the problem and explaining how your application solves it. Your tech list is on target as well - perhaps just a note to yourself (or item on project plan) be sure to update it as you learn more about each technology. 

**User stories**

Your MVP user stories feel like they are right-sized for the semester while meeting the requirements of Ent Java - for example, full CRUD and use of a service (find within an area). You did a nice job differentiating what actions can be taken by anyone who is not logged in (camper) versus logged in users.

- [x] Should have a sign out user story too so that nobody could access a user's account. This is not a heavy lift - essentially invalidating the session.


**Project plan**

This is probably one of the most challenging parts at this point and you did a very good job capturing much of what needs to happen to bring this to a code-complete version 1.  As you learn more about the various tech, I suspect you'll be able to add more detail here, but right now I don't see anything major missing. 

**Screen design**

Great job here - all user stories appear to be represented in the screens. 

One thing to note is that we'll be using AWS Cognito for sign up/log-in and Cognito can provide the screens for this.  You can also use your own, but just wanted to mention it in case you want to save a bit of time. 

**Reflection statements/Time Log**

Great work consistently tracking!

- [x] You do not have to use three documents for this unless you find it beneficial- one is fine. If you aren't going to use the Journal or Reflection documents, you can delete them.

**Other**

- [x] I noticed some logs and property files which could contain information like usernames, passwords, etc. It would be a good idea to remove these from GitHub and add them to .gitignore. If you aren't able to find the details on how to do this, please post in slack as I'm sure other will run into this too!

**Comment by jbjohnson2** [comment]
I removed the journal but kept the reflection file in my project incase I want to add more information about my project work at some point. 
I think I removed all of the config and properties files that I needed to and added those files to my git ignore. I think it was just the things in the resources directories that needed to be  ignored.
I added a user story about signing out.
